import type { Listing, SocialPost } from '@/types'
import type { ServiceListing } from '@/types/bartr-b'

// Placeholder listings used when the DB returns nothing.
// They look exactly like real listings — same card anatomy, same detail page.
// IDs use the prefix "demo-" so the listing detail page knows to skip the DB fetch.
export const DEMO_LISTINGS: Listing[] = [
  {
    id: 'demo-1',
    user_id: 'demo',
    title: 'Fujifilm X-T20 + 18–55mm f/2.8-4 Kit',
    description: 'Bought new, used for maybe 40 shoots. Sensor pristine, no dust. Comes with original box, two batteries, charger and UV filter. One tiny scuff on the kit lens hood — not visible in shots.',
    category: 'Electronics',
    condition: 'good',
    value_estimate_low: 380,
    value_estimate_high: 460,
    wants: 'MacBook Air, iPad Pro, Audio gear, open to offers',
    location: 'London',
    images: [],
    status: 'active',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'demo-u1',
      handle: 'tessafilm',
      display_name: 'Tessa M.',
      avatar_url: null,
      bio: 'Documentary filmmaker. Trading down to go mirrorless.',
      tier: 'silver',
      location: 'London',
      verified_id: true,
      verified_phone: true,
      verified_photo: false,
      follower_count: 84,
      following_count: 31,
      trade_count: 12,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 200).toISOString(),
    },
  },
  {
    id: 'demo-2',
    user_id: 'demo',
    title: "Vintage Levi's 501 Denim Jacket — Washed Indigo, M",
    description: "Classic 80s cut, not the modern slim fit. Washed to that perfect faded indigo. Single breast pocket with copper rivets. No distressing — just natural fading from wear. Fits a modern medium perfectly.",
    category: 'Fashion',
    condition: 'good',
    value_estimate_low: 65,
    value_estimate_high: 90,
    wants: 'Film camera, photography books, vinyl, vintage tee',
    location: 'Bristol',
    images: [],
    status: 'active',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'demo-u2',
      handle: 'jordanmc',
      display_name: 'Jordan',
      avatar_url: null,
      bio: 'Thrift obsessive. Wardrobe rotation every season.',
      tier: 'bronze',
      location: 'Bristol',
      verified_id: false,
      verified_phone: true,
      verified_photo: false,
      follower_count: 22,
      following_count: 45,
      trade_count: 4,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    },
  },
  {
    id: 'demo-3',
    user_id: 'demo',
    title: 'Fender Squier Telecaster — Butterscotch Blonde',
    description: "Classic tele twang. Upgraded to a Graph Tech nut and new strings — plays way above its price bracket. Comes with a padded gig bag. Neck is straight, action set low. Ideal first guitar or backup.",
    category: 'Music',
    condition: 'good',
    value_estimate_low: 190,
    value_estimate_high: 250,
    wants: 'Synth, effects pedals, studio monitors, audio interface',
    location: 'Manchester',
    images: [],
    status: 'active',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'demo-u3',
      handle: 'mikeb',
      display_name: 'Mike B.',
      avatar_url: null,
      bio: 'Going electronic. Tele has to go.',
      tier: 'bronze',
      location: 'Manchester',
      verified_id: true,
      verified_phone: false,
      verified_photo: false,
      follower_count: 11,
      following_count: 8,
      trade_count: 2,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    },
  },
  {
    id: 'demo-4',
    user_id: 'demo',
    title: "Arc'teryx Beta AR Jacket — Black, L",
    description: "Gore-Tex Pro shell. Worn on maybe 15 days in the hills. All seams sealed, zips smooth, no delamination. The hood fits over a helmet. This jacket retails at £700 — offering it here before listing elsewhere.",
    category: 'Fashion',
    condition: 'like_new',
    value_estimate_low: 320,
    value_estimate_high: 400,
    wants: 'Snowboard gear, hiking boots, camping kit, quality backpack',
    location: 'Edinburgh',
    images: [],
    status: 'active',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'demo-u4',
      handle: 'pablor',
      display_name: 'Pablo R.',
      avatar_url: null,
      bio: 'Switched to trail running. Shedding the ski kit.',
      tier: 'silver',
      location: 'Edinburgh',
      verified_id: true,
      verified_phone: true,
      verified_photo: true,
      follower_count: 56,
      following_count: 21,
      trade_count: 9,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    },
  },
  {
    id: 'demo-5',
    user_id: 'demo',
    title: 'iPad Pro 11" (2021, M1) 128GB WiFi + Apple Pencil 2',
    description: "Immaculate screen — no scratches. Pencil pairs instantly, charges magnetically. Perfect for drawing, notes or as a second screen. Comes with Apple case and USB-C cable. Battery at 97% health.",
    category: 'Electronics',
    condition: 'like_new',
    value_estimate_low: 520,
    value_estimate_high: 640,
    wants: 'MacBook, camera body, keyboard + desk setup, open to bundles',
    location: 'London',
    images: [],
    status: 'active',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'demo-u5',
      handle: 'lilyc',
      display_name: 'Lily C.',
      avatar_url: null,
      bio: 'Designer. Upgrading the whole setup.',
      tier: 'gold',
      location: 'London',
      verified_id: true,
      verified_phone: true,
      verified_photo: true,
      follower_count: 203,
      following_count: 67,
      trade_count: 28,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 400).toISOString(),
    },
  },
  {
    id: 'demo-6',
    user_id: 'demo',
    title: 'Technics SL-1200MK2 Turntable — Silver',
    description: "Legendary direct drive. New needle fitted 6 months ago, still going strong. Dust cover perfect, no cracks. Pitch control accurate. I've used it for home listening only — not a club deck.",
    category: 'Music',
    condition: 'good',
    value_estimate_low: 440,
    value_estimate_high: 540,
    wants: 'Vinyl collection (200+), hi-fi separates, speakers, amp',
    location: 'Glasgow',
    images: [],
    status: 'active',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'demo-u6',
      handle: 'djsol',
      display_name: 'DJ Sol',
      avatar_url: null,
      bio: 'Moving from analog to digital.',
      tier: 'silver',
      location: 'Glasgow',
      verified_id: true,
      verified_phone: false,
      verified_photo: false,
      follower_count: 138,
      following_count: 44,
      trade_count: 17,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 250).toISOString(),
    },
  },
  {
    id: 'demo-7',
    user_id: 'demo',
    title: 'Philosophy Library — 12 Hardbacks',
    description: "Curated set: Nietzsche, Camus, Simone de Beauvoir, Sartre, Hannah Arendt, Wittgenstein, Bertrand Russell and more. All first UK hardback editions where possible. No annotations. Condition: fine to very good.",
    category: 'Books',
    condition: 'good',
    value_estimate_low: 55,
    value_estimate_high: 80,
    wants: 'Literary fiction, art books, architecture books, journals',
    location: 'Oxford',
    images: [],
    status: 'active',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'demo-u7',
      handle: 'samirk',
      display_name: 'Samir K.',
      avatar_url: null,
      bio: 'Switching my reading list. Philosophy out, fiction in.',
      tier: 'bronze',
      location: 'Oxford',
      verified_id: false,
      verified_phone: true,
      verified_photo: false,
      follower_count: 7,
      following_count: 14,
      trade_count: 1,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    },
  },
  {
    id: 'demo-8',
    user_id: 'demo',
    title: 'Nike Air Max 1 OG Anniversary — UK 9 (DS)',
    description: "Deadstock. Never worn, original box, extra lace set. Anniversary colourway (red/grey). These are impossible to find in UK 9 right now. Seriously considering keeping them — make me a decent offer.",
    category: 'Fashion',
    condition: 'new',
    value_estimate_low: 140,
    value_estimate_high: 185,
    wants: 'Jordan 1s, New Balance 550/574, Off-White anything, Supreme',
    location: 'London',
    images: [],
    status: 'active',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'demo-u8',
      handle: 'kwamea',
      display_name: 'Kwame A.',
      avatar_url: null,
      bio: 'Sneaker collector. Rotating the rotation.',
      tier: 'silver',
      location: 'London',
      verified_id: true,
      verified_phone: true,
      verified_photo: false,
      follower_count: 91,
      following_count: 33,
      trade_count: 14,
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    },
  },
]

export const DEMO_POSTS: SocialPost[] = [
  {
    id: 'demo-p1',
    user_id: 'demo-u5',
    type: 'trade_win',
    content: "Just swapped my old Fujifilm X100V for a MacBook Air M2. Both valued around £900. Perfect fair trade — zero cash, zero drama. This platform is exactly what I needed. 🙌",
    listing_id: null,
    trade_id: null,
    like_count: 24,
    comment_count: 5,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    has_liked: false,
    profile: {
      id: 'demo-u5',
      handle: 'lilyc',
      display_name: 'Lily C.',
      avatar_url: null,
      bio: null,
      tier: 'gold',
      location: 'London',
      verified_id: true,
      verified_phone: true,
      verified_photo: true,
      follower_count: 203,
      following_count: 67,
      trade_count: 28,
      created_at: '',
    },
  },
  {
    id: 'demo-p2',
    user_id: 'demo-u4',
    type: 'accepted_pattern',
    content: "Tip for anyone listing outdoor gear: be specific about the spec. I listed my Arc'teryx jacket as 'Gore-Tex Pro, L' and got 6 offers in 48hrs. Vague listings sit dead for weeks.",
    listing_id: null,
    trade_id: null,
    like_count: 18,
    comment_count: 3,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    has_liked: false,
    profile: {
      id: 'demo-u4',
      handle: 'pablor',
      display_name: 'Pablo R.',
      avatar_url: null,
      bio: null,
      tier: 'silver',
      location: 'Edinburgh',
      verified_id: true,
      verified_phone: true,
      verified_photo: true,
      follower_count: 56,
      following_count: 21,
      trade_count: 9,
      created_at: '',
    },
  },
  {
    id: 'demo-p3',
    user_id: 'demo-u6',
    type: 'looking_for',
    content: "Looking for a decent vinyl collection — 200+ records, any genre. I have a Technics SL-1200MK2 ready to trade. London/Glasgow only for something this big. DM me.",
    listing_id: 'demo-6',
    trade_id: null,
    like_count: 11,
    comment_count: 7,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    has_liked: false,
    profile: {
      id: 'demo-u6',
      handle: 'djsol',
      display_name: 'DJ Sol',
      avatar_url: null,
      bio: null,
      tier: 'silver',
      location: 'Glasgow',
      verified_id: true,
      verified_phone: false,
      verified_photo: false,
      follower_count: 138,
      following_count: 44,
      trade_count: 17,
      created_at: '',
    },
    listing: DEMO_LISTINGS.find(l => l.id === 'demo-6'),
  },
  {
    id: 'demo-p4',
    user_id: 'demo-u1',
    type: 'trade_win',
    content: "Third trade done on Bartr. Camera gear → camera gear. This community actually works. People are honest, trades are fair, meetups are easy. No awkward PayPal requests mid-swap.",
    listing_id: null,
    trade_id: null,
    like_count: 32,
    comment_count: 8,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    has_liked: false,
    profile: {
      id: 'demo-u1',
      handle: 'tessafilm',
      display_name: 'Tessa M.',
      avatar_url: null,
      bio: null,
      tier: 'silver',
      location: 'London',
      verified_id: true,
      verified_phone: true,
      verified_photo: false,
      follower_count: 84,
      following_count: 31,
      trade_count: 12,
      created_at: '',
    },
  },
  {
    id: 'demo-p5',
    user_id: 'demo-u7',
    type: 'joined',
    content: "New here. Trying to trade out my philosophy library for literary fiction. Anyone into Nietzsche and wants to offload some Donna Tartt?",
    listing_id: 'demo-7',
    trade_id: null,
    like_count: 6,
    comment_count: 4,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    has_liked: false,
    profile: {
      id: 'demo-u7',
      handle: 'samirk',
      display_name: 'Samir K.',
      avatar_url: null,
      bio: null,
      tier: 'bronze',
      location: 'Oxford',
      verified_id: false,
      verified_phone: true,
      verified_photo: false,
      follower_count: 7,
      following_count: 14,
      trade_count: 1,
      created_at: '',
    },
    listing: DEMO_LISTINGS.find(l => l.id === 'demo-7'),
  },
]

export const DEMO_SERVICES: ServiceListing[] = [
  {
    id: 'dsvc-1',
    user_id: 'demo',
    title: 'Brand identity design — logo, palette, typography system',
    description: 'I design brand identities for startups and small businesses. Deliverables: wordmark, icon variant, colour system, type scale, usage guide. Figma source included.',
    category: 'Design',
    skills: ['Figma', 'Branding', 'Typography'],
    delivery_time_days: 10,
    credit_rate: 120,
    credit_unit: 'per project',
    portfolio_urls: [],
    is_available: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'dsvc-u1',
      handle: 'ninab',
      display_name: 'Nina B.',
      avatar_url: null,
      bio: 'Brand designer. 8 years. ex-agency.',
      tier: 'gold',
      location: 'London',
      verified_id: true,
      verified_phone: true,
      verified_photo: false,
      follower_count: 142,
      following_count: 38,
      trade_count: 22,
      created_at: '',
    },
  },
  {
    id: 'dsvc-2',
    user_id: 'demo',
    title: 'React / Next.js frontend development',
    description: 'Building React and Next.js apps, component libraries, landing pages and dashboards. Clean, typed code. Available for short sprints or ongoing retainer.',
    category: 'Development',
    skills: ['React', 'Next.js', 'TypeScript'],
    delivery_time_days: null,
    credit_rate: 18,
    credit_unit: 'per hour',
    portfolio_urls: [],
    is_available: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'dsvc-u2',
      handle: 'omari_dev',
      display_name: 'Omari K.',
      avatar_url: null,
      bio: 'Frontend engineer. Building in public.',
      tier: 'silver',
      location: 'Manchester',
      verified_id: true,
      verified_phone: false,
      verified_photo: false,
      follower_count: 67,
      following_count: 24,
      trade_count: 9,
      created_at: '',
    },
  },
  {
    id: 'dsvc-3',
    user_id: 'demo',
    title: 'B2B copywriting — website, emails, product docs',
    description: 'Conversion-focused copy for SaaS and B2B companies. Specialisms: homepage, onboarding emails, pricing page, release notes. Research-first process.',
    category: 'Writing',
    skills: ['Copywriting', 'SaaS', 'Email'],
    delivery_time_days: 7,
    credit_rate: 40,
    credit_unit: 'per 1000 words',
    portfolio_urls: [],
    is_available: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'dsvc-u3',
      handle: 'priya_writes',
      display_name: 'Priya S.',
      avatar_url: null,
      bio: 'Writer. Former journalist, now SaaS copy.',
      tier: 'silver',
      location: 'London',
      verified_id: true,
      verified_phone: true,
      verified_photo: true,
      follower_count: 88,
      following_count: 41,
      trade_count: 16,
      created_at: '',
    },
  },
  {
    id: 'dsvc-4',
    user_id: 'demo',
    title: 'Product photography — clean white background + lifestyle',
    description: 'Studio product photography for e-commerce and marketplaces. White background, lifestyle, detail shots. 24hr turnaround. Based in Edinburgh — will travel for larger shoots.',
    category: 'Photography',
    skills: ['Product photography', 'Studio', 'Retouching'],
    delivery_time_days: 2,
    credit_rate: 60,
    credit_unit: 'per half-day',
    portfolio_urls: [],
    is_available: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'dsvc-u4',
      handle: 'angie_lens',
      display_name: 'Angie T.',
      avatar_url: null,
      bio: 'Commercial photographer. 10yr+ Edinburgh.',
      tier: 'gold',
      location: 'Edinburgh',
      verified_id: true,
      verified_phone: true,
      verified_photo: true,
      follower_count: 211,
      following_count: 55,
      trade_count: 31,
      created_at: '',
    },
  },
  {
    id: 'dsvc-5',
    user_id: 'demo',
    title: 'Growth strategy + SEO audit for early-stage startups',
    description: 'I work with pre-Series A startups on organic growth. Deliverables: SEO audit, content strategy, 90-day growth roadmap. Remote. Async-friendly.',
    category: 'Marketing',
    skills: ['SEO', 'Content strategy', 'Growth'],
    delivery_time_days: 14,
    credit_rate: 90,
    credit_unit: 'per engagement',
    portfolio_urls: [],
    is_available: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'dsvc-u5',
      handle: 'marcot',
      display_name: 'Marco T.',
      avatar_url: null,
      bio: 'ex-Notion growth. Now independent.',
      tier: 'gold',
      location: 'Remote',
      verified_id: true,
      verified_phone: true,
      verified_photo: false,
      follower_count: 304,
      following_count: 112,
      trade_count: 44,
      created_at: '',
    },
  },
  {
    id: 'dsvc-6',
    user_id: 'demo',
    title: 'Short-form video editing — Reels, TikTok, YouTube Shorts',
    description: 'Fast, punchy edits for social video. Bring me the raw footage and a reference reel — I\'ll deliver a cut within 24 hours. Captions, colour grade, music included.',
    category: 'Video',
    skills: ['Premiere Pro', 'After Effects', 'Captions'],
    delivery_time_days: 1,
    credit_rate: 25,
    credit_unit: 'per video',
    portfolio_urls: [],
    is_available: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    updated_at: new Date().toISOString(),
    profile: {
      id: 'dsvc-u6',
      handle: 'dex_cuts',
      display_name: 'Dexter N.',
      avatar_url: null,
      bio: 'Video editor. 500+ videos delivered.',
      tier: 'silver',
      location: 'Birmingham',
      verified_id: false,
      verified_phone: true,
      verified_photo: false,
      follower_count: 73,
      following_count: 29,
      trade_count: 11,
      created_at: '',
    },
  },
]

// ─── Demo message threads ──────────────────────────────────────────────────
// These represent realistic trade conversations shown in the Messages inbox
// when there is no authenticated user. Interactive — accept/decline work in
// client-side state so the visitor experiences the full flow.

export interface DemoMessage {
  id: string
  content: string
  is_me: boolean        // true = right-aligned (the visitor)
  handle: string
  display_name: string
  created_at: string
  is_offer_summary?: boolean
}

export interface DemoThread {
  id: string
  listing: Listing
  other_display_name: string
  other_handle: string
  offer: {
    id: string
    status: 'pending' | 'accepted' | 'declined' | 'completed'
    offered_items: Array<{ title: string; value_low: number; value_high: number }>
    topup_amount: number | null
    topup_currency: string | null
  }
  messages: DemoMessage[]
  last_message: string
  last_message_at: string
}

export const DEMO_THREADS: DemoThread[] = [
  // Thread 1 — pending offer. Tessa wants to swap her camera for YOUR imaginary listing.
  // The visitor plays the role of the person receiving the offer.
  {
    id: 'demo-thread-1',
    listing: DEMO_LISTINGS[0], // Fujifilm X-T20
    other_display_name: 'Tessa M.',
    other_handle: 'tessafilm',
    offer: {
      id: 'demo-offer-1',
      status: 'pending',
      offered_items: [
        { title: 'Sony WH-1000XM4 Headphones', value_low: 180, value_high: 220 },
      ],
      topup_amount: null,
      topup_currency: null,
    },
    messages: [
      {
        id: 'dm1-1',
        content: "Hi! Love the camera listing. I have Sony WH-1000XM4 headphones — nearly new, original box. Would you consider a straight swap? Both around the £200 mark.",
        is_me: false,
        handle: 'tessafilm',
        display_name: 'Tessa M.',
        created_at: new Date(Date.now() - 1000 * 60 * 47).toISOString(),
      },
      {
        id: 'dm1-2',
        content: "Offer sent: Sony WH-1000XM4 Headphones (£180–220)",
        is_me: false,
        handle: 'tessafilm',
        display_name: 'Tessa M.',
        created_at: new Date(Date.now() - 1000 * 60 * 46).toISOString(),
        is_offer_summary: true,
      },
      {
        id: 'dm1-3',
        content: "Hey Tessa! They look great. Are these the current gen with the multipoint Bluetooth?",
        is_me: true,
        handle: 'you',
        display_name: 'You',
        created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      },
      {
        id: 'dm1-4',
        content: "Yes — XM4, 2022 model. Firmware updated. I used them for about 6 months then switched to in-ears for the gym. No scratches, carrying case included.",
        is_me: false,
        handle: 'tessafilm',
        display_name: 'Tessa M.',
        created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      },
    ],
    last_message: "Yes — XM4, 2022 model. Firmware updated…",
    last_message_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },

  // Thread 2 — accepted offer. You made an offer on a turntable, it was accepted.
  // Now coordinating the meetup.
  {
    id: 'demo-thread-2',
    listing: DEMO_LISTINGS[5], // Technics SL-1200MK2
    other_display_name: 'DJ Sol',
    other_handle: 'djsol',
    offer: {
      id: 'demo-offer-2',
      status: 'accepted',
      offered_items: [
        { title: "Arc'teryx Beta AR Jacket — Black, L", value_low: 320, value_high: 400 },
      ],
      topup_amount: null,
      topup_currency: null,
    },
    messages: [
      {
        id: 'dm2-1',
        content: "Offer: Arc'teryx Beta AR Jacket — Black, L (£320–400)",
        is_me: true,
        handle: 'you',
        display_name: 'You',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        is_offer_summary: true,
      },
      {
        id: 'dm2-2',
        content: "Oh that's interesting — I've been looking for a proper shell for winter. Can you share more details on condition?",
        is_me: false,
        handle: 'djsol',
        display_name: 'DJ Sol',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 4.5).toISOString(),
      },
      {
        id: 'dm2-3',
        content: "Barely worn — maybe 15 days out. All seams sealed, zips smooth. Size L, fits a standard large. I can meet in Glasgow next weekend.",
        is_me: true,
        handle: 'you',
        display_name: 'You',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      },
      {
        id: 'dm2-4',
        content: "Deal! Offer accepted. I'm in the West End — Kelvingrove area works for me Saturday afternoon?",
        is_me: false,
        handle: 'djsol',
        display_name: 'DJ Sol',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      },
      {
        id: 'dm2-5',
        content: "Perfect. Saturday 2pm at Kelvingrove. I'll bring the jacket, you bring the turntable. See you then! 🤝",
        is_me: true,
        handle: 'you',
        display_name: 'You',
        created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      },
    ],
    last_message: "Perfect. Saturday 2pm at Kelvingrove…",
    last_message_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },

  // Thread 3 — completed trade. Logged on the public ledger.
  {
    id: 'demo-thread-3',
    listing: DEMO_LISTINGS[4], // iPad Pro
    other_display_name: 'Lily C.',
    other_handle: 'lilyc',
    offer: {
      id: 'demo-offer-3',
      status: 'completed',
      offered_items: [
        { title: 'Philosophy Library — 12 Hardbacks', value_low: 55, value_high: 80 },
        { title: 'Fender Squier Telecaster', value_low: 190, value_high: 250 },
      ],
      topup_amount: 200,
      topup_currency: 'GBP',
    },
    messages: [
      {
        id: 'dm3-1',
        content: "Offer: Philosophy Library (£55–80) + Fender Squier Telecaster (£190–250) + £200 GBP top-up intent",
        is_me: false,
        handle: 'lilyc',
        display_name: 'Lily C.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
        is_offer_summary: true,
      },
      {
        id: 'dm3-2',
        content: "That's a creative bundle! The guitar's a surprise. The top-up covers the value gap nicely. I'll accept.",
        is_me: true,
        handle: 'you',
        display_name: 'You',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      },
      {
        id: 'dm3-3',
        content: "Brilliant. Met at Lily's studio in Shoreditch. Guitar, books and the iPad all swapped in person. Great vibe.",
        is_me: false,
        handle: 'lilyc',
        display_name: 'Lily C.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      },
      {
        id: 'dm3-4',
        content: "Trade complete ✓ — logged on the public ledger.",
        is_me: true,
        handle: 'you',
        display_name: 'You',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      },
    ],
    last_message: "Trade complete ✓ — logged on the public ledger.",
    last_message_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
]
